build:
  stage: build
  image: ruby:3.3
  script:
    - bundle config path vendor/bundle
    - bundle install
    - bundle exec jekyll b -d "_site"
  cache:
    paths:
      - vendor/bundle
  artifacts:
    paths:
      - _site
  only:
    - master
    - main

pages:
  stage: deploy
  script:
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - master
    - main
