renovate:
  stage: test
  image: renovate/renovate:latest
  variables:
    RENOVATE_PLATFORM: "gitlab"
    RENOVATE_REPOSITORIES: $CI_PROJECT_PATH
  script:
    - renovate
  only:
    - schedules
    - web
    - main
    - master

build-npm:
  stage: build
  image: node:23
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - assets/js/dist
  cache:
    paths:
      - node_modules
  only:
    - master
    - main
    - ^renovate\/.*$
    - merge_requests

build:
  stage: build
  image: ruby:3.4
  script:
    - bundle config path vendor/bundle
    - bundle install
    - bundle exec jekyll b -d "_site"
  cache:
    paths:
      - vendor/bundle
  artifacts:
    paths:
      - _site
  needs:
    - build-npm
  only:
    - master
    - main
    - ^renovate\/.*$
    - merge_requests

pages:
  stage: deploy
  needs:
    - build
  variables:
    FF_USE_FASTZIP: "true"
    ARTIFACT_COMPRESSION_LEVEL: "fastest"
  script:
    - mv _site public
    - find public -type f -regex '.*\.\(htm\|html\|xml\|txt\|text\|js\|css\|svg\)$' -exec gzip -f -k {} \;
    - find public -type f -regex '.*\.\(htm\|html\|xml\|txt\|text\|js\|css\|svg\)$' -exec brotli -f -k {} \;
  pages: true
  artifacts:
    paths:
      - public
  only:
    - master
    - main
