renovate:
  stage: test
  image: renovate/renovate:latest
  variables:
    RENOVATE_PLATFORM: "gitlab"
    RENOVATE_REPOSITORIES: $CI_PROJECT_PATH
  script:
    - renovate
  only:
    - schedules
    - web
    - main
    - master

build-npm:
  stage: build
  image: node:22
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - assets/js/dist
  only:
    - master
    - main
    - ^renovate\/.*$
    - merge_requests

build:
  stage: build
  image: ruby:3.4
  script:
    - bundle config path vendor/bundle
    - bundle install
    - bundle exec jekyll b -d "_site"
  cache:
    paths:
      - vendor/bundle
  artifacts:
    paths:
      - _site
  needs:
    - build-npm
  only:
    - master
    - main
    - ^renovate\/.*$
    - merge_requests

pages:
  stage: deploy
  needs:
    - build
  script:
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - master
    - main
